import type { NextPage } from 'next'
import Head from 'next/head'
import TestBoy from '../components/TestBoy'

const Home: NextPage = () => {
	return (
		<div data-theme="cmyk" className="h-screen">
			<Head>
				<title>DnD Below</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon-192x192.png" />
				<link rel="manifest" href="/manifest.json" />
			</Head>
			<div className="grid grid-cols-1 justify-center align-center h-max">
				<TestBoy />
			</div>
		</div>
	)
}

export default Home
