import type { NextPage } from 'next'
import Head from 'next/head'
import BodyContainer from '../components/UI/BodyContainer'
import TestBoy from '../components/TestBoy'

const Home: NextPage = () => {
	return (
		// data-theme="night"
		<div data-theme="night">
			<Head>
				<title>DnD Below</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon-192x192.png" />
				<link rel="manifest" href="/manifest.json" />
			</Head>
			<BodyContainer>
				<TestBoy />
				<TestBoy />
				<TestBoy />
				<TestBoy />
				<TestBoy />
				<TestBoy />
			</BodyContainer>
		</div>
	)
}

export default Home
